name: Build
on:
  push:
    branches: [ master, glic-2.34 ]
  pull_request:
    branches:
      - master
  workflow_dispatch:


permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    container: almalinux:9
    strategy:
      fail-fast: false
      matrix:
        # os: [windows-latest, macos-15, ubuntu-24.04, ubuntu-24.04-arm]
        os: [ubuntu-24.04]
    steps:
      - name: Setup Windows
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1
      - name: Setup NASM for Windows
        if: matrix.os == 'windows-latest'
        uses: ilammy/setup-nasm@v1.2.1
      - name: Install dependencies
        run: |
          dnf install -y git make gcc-c++ gzip which clang cmake zlib-devel openssl-devel
          ln -s /usr/bin/clang /usr/bin/clang-18
          ln -s /usr/bin/clang++ /usr/bin/clang++-18
          /usr/lib64/libc.so.6

      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build binaries
        run: |
          # git clone --recursive https://github.com/uNetworking/uWebSockets.js.git
          # cd uWebSockets.js

          # No clones, we build what we checked out
          ${{ matrix.os == 'windows-latest' && 'nmake' || 'make' }}
          ls dist
          cd tests && npm install ws && node smoke.js && cd ..
          ls dist

          # git fetch origin binaries:binaries
          # git checkout binaries
          # cp dist/*.node .
          # cp dist/*.js .
          # git rev-parse master > source_commit
          # ls
          # ${{ matrix.os != 'windows-latest' && 'git checkout master docs/index.d.ts && mv docs/index.d.ts .' || '' }}
          # git status
          # git config --global user.email "alexhultman@gmail.com"
          # git config --global user.name "Alex Hultman"
          # git commit -a -m "[GitHub Actions] Updated ${{ matrix.os }} binaries" || true
          # git push "https://unetworkingab:${{ secrets.SECRET }}@github.com/uNetworking/uWebSockets.js" binaries

      - name: Publish to alma9-binaries branch
        if: github.event_name != 'pull_request'
        run: |
          git config --global user.email "victor0801@gmail.com"
          git config --global user.name "jimmyolo"
          
          # Fix git safe directory
          git config --global --add safe.directory '*'

          # Stash artifacts
          mkdir -p /tmp/dist
          cp dist/*.node /tmp/dist/
          cp dist/*.js /tmp/dist/
          cp package.json /tmp/dist/
          cp docs/index.d.ts /tmp/dist/

          ls /tmp/dist
          
          # Fetch/Checkout target branch
          git fetch origin alma9-binaries || true
          if git rev-parse --verify origin/alma9-binaries >/dev/null 2>&1; then
            git checkout alma9-binaries
          else
            git checkout --orphan alma9-binaries
            git rm -rf .
          fi

          # Restore artifacts
          cp /tmp/dist/*.node .
          cp /tmp/dist/*.js .
          cp /tmp/dist/package.json .
          cp /tmp/dist/index.d.ts .

          # Commit
          git add *.node *.js package.json index.d.ts
          git commit -m "[GitHub Actions] Updated binaries"
          git push origin alma9-binaries

          # Tagging
          VERSION=$(node -p "require('./package.json').version")
          if [ -n "$VERSION" ]; then
            git tag -f "v${VERSION}"
            git push -f origin "v${VERSION}"
          fi

      # - name: Publish to GitHub Packages (required token)
      #   if: github.event_name != 'pull_request'
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     # Prepare package directory
      #     mkdir -p npm-package
      #     cp dist/*.node npm-package/
      #     cp dist/*.js npm-package/
      #     cp package.json npm-package/
      #     cp docs/index.d.ts npm-package/